### ISSUE TITLE
Issue with dots in routing name

### ISSUE THREAD

**Issue by wimurk** [whitecube/nova-page#16]
### PSR
When running the command `php artisan make:template AboutUs` the package creates a template with the name `About_us` this conflicts with the rest of the laravel code (uppercase words) `MyControllerHere.php` 

### routing
Next when changed the template name to `AboutUs` and creating a route like : 
```
Route::get('/about-us', 'Home\AboutUsController@index')->middleware('loadNovaPage')
    ->template(\App\Nova\Templates\AboutUs::class)
    ->name('about.us');
```
![image](https://user-images.githubusercontent.com/14072334/52705492-51bbe380-2f83-11e9-88ba-eec3117f8502.png)

Looks like the dot is removed ?

#### Front
![image](https://user-images.githubusercontent.com/14072334/52705615-a2334100-2f83-11e9-9064-37d3112b1aa7.png)

Don't know if i am missing something

**Comment by voidgraphics** [comment]
The class name is a bug. It definitely should be uppercase words.

I'm not sure what is causing the route to be cut at the dot, I will investigate and get back to you.

The last one is because the json file is missing from your system. I think it should be auto-created when you run the `make:template` command, so I will add that and it will be available in the next release.

Thanks for bringing these to our attention.

**Comment by wimurk** [comment]
In the template command the line 
`$name = ucfirst(snake_case($this->getNameArgument()));`
change to 
`$name = ucwords($this->getNameArgument());`

**Comment by otaviogui** [comment]
Could you show Controller, please ?

**Comment by wimurk** [comment]
I fixed  the issue with the dot in https://github.com/whitecube/nova-page/pull/17
The problem was the explode on the name for the type and key variable.

Changing it to explode only on the first dot, fixes the issue
