### ISSUE TITLE
Tabs in Pages

### ISSUE THREAD

**Issue by Krato** [whitecube/nova-page#24]
Hello, I'm trying to use [Nova Tabs](https://github.com/eminiarts/nova-tabs) for a template.

But when I add the trait for see tabs on edit views (`TabsOnEdit` trait), throws an error:

```php
Cannot make non static method Whitecube\NovaPage\Pages\Template::fill() static 
in class Eminiarts\Tabs\TabsOnEdit
```
<img width="1391" alt="Captura de pantalla 2019-03-09 a las 20 58 55" src="https://user-images.githubusercontent.com/74367/54076669-73706800-42ae-11e9-88ed-299fc2354ed9.png">

Thank you.

**Comment by voidgraphics** [comment]
This is because the `fill` method in Nova Resources is declared as static, which Nova Tabs then overrides with its `TabsOnEdit` trait.

[Our implementation of the fill method](https://github.com/eminiarts/nova-tabs/blob/master/src/TabsOnEdit.php#L14) is not static, so it breaks.

What's your take on this @Nyratas? Could we possibly make our fill method static?

**Comment by Krato** [comment]
Thats will be great. Thanks to think about.

**Comment by Nyratas** [comment]
We will take a look why our `fill` method is not static and does not break any of the Templates behavior. But even if we make it static, keep in mind that this doesn't guarantee a full compatibility with Nova Tabs since Templates are not Models.

**Comment by Krato** [comment]
Yes I know. Hope that works fine :)
