### ISSUE TITLE
If Statements around fields in blade templates

### ISSUE THREAD

**Issue by DCReddish97** [whitecube/nova-page#38]
I'm trying to set an IF statement around the fields pulled through Nova-page tool

e.g @if (!empty(Page::get('sub_title'))))

But everything I'm trying just seems to be ignored and Laravel throws an error if the field is left empty.

**Comment by voidgraphics** [comment]
Since 7c9d47f86b8d76218538634d49e2278fe8f6820f it should not throw an exception by default anymore (see https://github.com/whitecube/nova-page/issues/31#issuecomment-495183748) and just fail silently. However I'm noticing that a proper release including these changes has not been published yet and is still in draft status. I suppose you can try changing your version to `dev-master` if this is an urgent matter, but I recommend you hang on until we can get around to finishing that release properly.

I will tag @Nyratas in here so he doesn't lose sight of this.
