### ISSUE TITLE
Remove template declaration in routes

### ISSUE THREAD

**Issue by keizah7** [whitecube/nova-page#85]
I have made translated routes, and after declaring template in all routes I got three static pages even I have one row in table.
![image](https://user-images.githubusercontent.com/49227202/143189046-d750ed1c-bc20-4b91-9f0b-588491fe142a.png)
It would be nice have availability static_pages without declaration of template. We using static pages directly by query

**Comment by Nyratas** [comment]
Hi @keizah7, you shouldn't handle translated pages with different routes. There are better ways to do that and exploiting them will also give better results in nova-page. The solution we use for translated is [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization).

**Comment by keizah7** [comment]
Your mentioned package doesn't translate route it self. It is not suitable for out situation, thats why we using custom solution. Can you add our request to your backlog. It's kind a bug too

**Comment by Nyratas** [comment]
The mentioned package [does translate routes](https://github.com/mcamara/laravel-localization#translated-routes). It even has a whole section dedicated to it in their docs.

The method you're using is not a a viable multilingual architecture. Your request won't be treated in this package since it's certainly not a bug.
